### PR TITLE
Add sorting to ID mapping results.

### PR DESCRIPTION
**Pull request by dlrice**
## Purpose
Get column sorting in ID mapping results working
https://www.ebi.ac.uk/panda/jira/browse/TRM-27602

(Peptide search sorting doesn't work because the accessions endpoint doesn't currently support this but I'm about to write a jira for this)

## Approach

- When updating column sort use `history.location.pathname` rather than the corresponding `SearchResultsLocations[namespace]`
- Add `sort` param to ID mapping results API request

## Testing
Manual

## Checklist
- [x] My PR is scoped properly, and “does one thing only”
- [x] I have reviewed my own code
- [x] I have checked that linting checks pass and type safety is respected
- [x] I have checked that tests pass and coverage has at least improved, and if not explained the reasons why

### CODE REVIEW

**Comment by aurel-l** [comment]
I'm getting a `/overview?&sort=id&dir=ascend` URL (notice the `?&`). While this still works, it doesn't look really nice

**Comment by aurel-l** [comment]
> Add sort param to ID mapping results API request
Should that be also in the URL generated for the API?

**Comment by dlrice** [comment]
> > Add sort param to ID mapping results API request
> 
> Should that be also in the URL generated for the API in the panel?

Yes, I'm seeing this happening for tabular files - do you have an example where this isn't happening?

**Comment by aurel-l** [comment]
> > > Add sort param to ID mapping results API request
> > 
> > 
> > Should that be also in the URL generated for the API in the panel?
> 
> Yes, I'm seeing this happening for tabular files - do you have an example where this isn't happening?

Ah I see. So is this on purpose that we don't allow that in non-tabular format? I'm just thinking that it might be useful to order FASTA format by entry name for example, or by any field, even though the format doesn't allow to display that specific column.

This is not blocking then, since I see that this is working with tabular format

**Review by aurel-l — APPROVED** [review]

**Comment by dlrice** [comment]
> Ah I see. So is this on purpose that we don't allow that in non-tabular format? I'm just thinking that it might be useful to order FASTA format by entry name for example, or by any field, even though the format doesn't allow to display that specific column.

I hadn't even thought of this - I agree that could be useful. I think this would be a good improvement and the backend does support this. I've had a look and it's a simple code change so will just put it in this PR

**Review by aurel-l — APPROVED** [review]

**Pull request merged**
