### PR TITLE
Handle 303 redirects

### PR DESCRIPTION
**Pull request by its-mahdi**
- [x] What is the link to the Jira that this PR is for?
https://www.ebi.ac.uk/panda/jira/browse/TRM-23974
- [x] Have you written tests and do these have >= 75% coverage of the code that you are contributing?
- [x] Is it possible to visually evaluate this PR in the browser? If so, what are the steps to do this (eg specific URLs or sections)?
Go to: http://localhost:8080/uniprotkb/Q14301
Make sure you see an in-page message, notifying you about the 303 redirect.
- [ ] Are there any linting errors that required you to add exceptions?
- [ ] If there are backend requests, have you checked for the existence of the resource's attributes before attempting access?

### CODE REVIEW

**Comment by its-mahdi** [comment]
I wasted many hours to figure out Axios mock responses are not exactly the same as browser responses. This bit looks a little bit hacky, but it's the best I could do:

https://github.com/ebi-uniprot/uniprot-website/blob/handle-303-redirects/src/shared/hooks/useDataApi.ts#L44-L56

**Comment by aurel-l** [comment]
> I wasted many hours to figure out Axios mock responses are not exactly the same as browser responses. This bit looks a little bit hacky, but it's the best I could do:
> 
> https://github.com/ebi-uniprot/uniprot-website/blob/handle-303-redirects/src/shared/hooks/useDataApi.ts#L44-L56

After investigating I saw there was an issue with casing of `responseURL`/`responseUrl` in the mocked response (so, part of `axios-mock-adapter`) compared to the axios response in the browser.
Ideally I think that'd need to be raised as an issue in the library, because it's weird to have a condition in the code just to have the tests work, that defeats a bit the purpose of doing tests.
Anyone else having an opinion on what we should do. Drop the corresponding test? Something else?
If we keep the test and the condition for the test to work, maybe I'd write it a more similar way just to make it clear it's the casing itself which is different, and not depend on another part of the axios API.
```

      if (
        action.response &&
        action.response.request.responseURL &&
        action.response.request.responseURL !== action.originalURL
      ) {
        newState.redirectedTo = action.response.request.responseURL;
      } else if (
        // Issue with casing in axios-mock-adapter?
        action.response &&
        action.response.request.responseUrl &&
        action.response.request.responseUrl !== action.originalURL
      ) {
        newState.redirectedTo = action.response.request.responseUrl;
      }
```

**Comment by its-mahdi** [comment]
I didn't realise that's just an alphabetic casing issue. I think your solution is better. Happy to reflect that in the code, if no one else has any better suggestions.

**Comment by xwatkins** [comment]
Agree I think someone should create a bug report and we could use @aurel-l 's code in the meantime with a link to the bug report in the comment:
https://github.com/ctimmerm/axios-mock-adapter/blob/master/src/handle_request.js#L30 is the offending line I think

**Comment by dlrice** [comment]
Why aren't other people struggling with this bug? I don't understand why not?!

**Comment by its-mahdi** [comment]
> Why aren't other people struggling with this bug? I don't understand why not?!

Probably because I am the only lucky one who hits the jackpot all the time!

**Pull request merged**
