### PR TITLE
switch default highlight to conservation

### PR DESCRIPTION
**Pull request by aurel-l**
- [x] What is the link to the Jira that this PR is for? [TRM-24991](https://www.ebi.ac.uk/panda/jira/browse/TRM-24991)
- [ ] Have you written tests and do these have >= 75% coverage of the code that you are contributing?
- [x] Is it possible to visually evaluate this PR in the browser? If so, what are the steps to do this (eg specific URLs or sections)? anywhere where we have a MSA viewer
- [ ] Are there any linting errors that required you to add exceptions?
- [ ] If there are backend requests, have you checked for the existence of the resource's attributes before attempting access?

Not as simple as expected:
Had to de-optimise the staggered rendering in wrapped view as the conservation highlight was disappearing when lower instances get added and the numbers on the right get longer and so push the grid's middle column to be smaller without the component detecting that it got resized. So, one way to solve that was to render everything in one go.
As an other way to optimise the page, I applied [this approach](https://web.dev/content-visibility/) to the MSA viewer as the space for the MSA viewer will be fixed once all the elements are rendered once.

### CODE REVIEW

**Review by dlrice — COMMENTED** [review]
Seeing several warnings:
```
pid_colors.js:16 Uncaught TypeError: Cannot read property 'S' of undefined
    at DynSchemeClass.push../node_modules/react-msa-viewer/src/colorschemes/pid_colors.js.pid.run [as getColor] (pid_colors.js:16)
    at ColorScheme.getColor (ColorScheme.js:25)
    at CanvasTilingGridComponent.drawTile (CanvasTilingGrid.js:38)
    at CanvasTilingGridComponent.draw (CanvasTilingGrid.js:103)
    at create (SequenceViewer.js:120)
    at CanvasCache.createTile (CanvasCache.js:56)
    at SequenceViewerComponent.renderTile (SequenceViewer.js:112)
    at SequenceViewerComponent.drawTiles (SequenceViewer.js:153)
    at SequenceViewerComponent.drawScene (SequenceViewer.js:70)
    at SequenceViewerComponent.draw (DraggingComponent.js:168)
```
with following sequences in align:
```
>sp|P05066|PHR_YEAST Deoxyribodipyrimidine photo-lyase, mitochondrial OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=PHR1 PE=1 SV=1
MKRTVISSSNAYASKRSRLDIEHDFEQYHSLNKKYYPRPITRTGANQFNNKSRAKPMEIV
EKLQKKQKTSFENVSTVMHWFRNDLRLYDNVGLYKSVALFQQLRQKNAKAKLYAVYVINE
DDWRAHMDSGWKLMFIMGALKNLQQSLAELHIPLLLWEFHTPKSTLSNSKEFVEFFKEKC
MNVSSGTGTIITANIEYQTDELYRDIRLLENEDHRLQLKYYHDSCIVAPGLITTDRGTNY
SVFTPWYKKWVLYVNNYKKSTSEICHLHIIEPLKYNETFELKPFQYSLPDEFLQYIPKSK
WCLPDVSEEAALSRLKDFLGTKSSKYNNEKDMLYLGGTSGLSVYITTGRISTRLIVNQAF
QSCNGQIMSKALKDNSSTQNFIKEVAWRDFYRHCMCNWPYTSMGMPYRLDTLDIKWENNP
VAFEKWCTGNTGIPIVDAIMRKLLYTGYINNRSRMITASFLSKNLLIDWRWGERWFMKHL
IDGDSSSNVGGWGFCSSTGIDAQPYFRVFNMDIQAKKYDPQMIFVKQWVPELISSENKRP
ENYPKPLVDLKHSRERALKVYKDAM
>sp|P05067|A4_HUMAN Amyloid-beta precursor protein OS=Homo sapiens OX=9606 GN=APP PE=1 SV=3
MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTK
TCIDTKEGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVG
EFVSDALLVPDKCKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFR
GVEFVCCPLAEESDNVDSADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEE
EADDDEDDEDGDEVEEEAEEPYEEATERTTSIATTTTTTTESVEEVVREVCSEQAETGPC
RAMISRWYFDVTEGKCAPFFYGGCGGNRNNFDTEEYCMAVCGSAMSQSLLKTTQEPLARD
PVKLPTTAASTPDAVDKYLETPGDENEHAHFQKAKERLEAKHRERMSQVMREWEEAERQA
KNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVEAMLNDRRRLALENYITAL
QAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRSQVMTHLRVIYER
MNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALMPSLTET
KTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEVEPVDARPAADRGLTTRPGSGLTN
IKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITL
VMLKKKQYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN
```

**Comment by dlrice** [comment]
The `content-visibility` property is nice but my only reservation is it's compatibility as it's only currently working in chrome. At least we will have graceful failure (at the cost of performance) in this case as everything will just render at once. I have tried BLASTing Titin (as you've suggested before) and it does cause the page to freeze so we will probably want to investigate some ways to dealing with large numbers of rows.

**Comment by dlrice** [comment]
> Seeing several warnings:
>
> pid_colors.js:16 Uncaught TypeError: Cannot read property 'S' of undefined
    at DynSchemeClass.push../node_modules/react-msa-viewer/src/colorschemes/pid_colors.js.pid.run [as getColor] (pid_colors.js:16)
    at ColorScheme.getColor (ColorScheme.js:25)
    at CanvasTilingGridComponent.drawTile (CanvasTilingGrid.js:38)...

Ignore this - I reinstalled my node modules and these errors are gone now.

**Review by dlrice — APPROVED** [review]

**Comment by aurel-l** [comment]
I got inspired this morning and figured out a way to fix this while keeping the staggered rendering. Instead of staggering the rendering of the whole wrapped row, I pass a flag to the row to tell it to delay the rendering of the nightingale components within the row. I also kept the `content-visibility` rule as it's improvement anyway, and it doesn't have any bad effect on browsers that don't support it.

**Pull request merged**
