### PR TITLE
2022 04 download uniparc & uniref

### PR DESCRIPTION
**Pull request by dlrice**
## Purpose

- Add TSV format to existing download dropdown in UniParc entry
- Add List format to existing download dropdown in UniRef entry 

## Approach

- Add new `apiUrls` for uniparc with databases endpoint
- Add exception for uniparc && tsv in `EntryDownload`
- Open file format selections in new tab
- Updated uniref members download to accommodate file format
- Blocked by not having tsv and xml for uniref members ([Jira](https://www.ebi.ac.uk/panda/jira/browse/TRM-27641))

## Testing
Added unit tests

## Checklist
- [x] My PR is scoped properly, and “does one thing only”
- [x] I have reviewed my own code
- [x] I have checked that linting checks pass and type safety is respected
- [x] I have checked that tests pass and coverage has at least improved, and if not explained the reasons why

### CODE REVIEW

**Comment by aurel-l** [comment]
Actually, same issue with UniRef members

**Comment by dlrice** [comment]
Good catches. Regarding streaming, I think the only thing we could possibly do is to ask backend to provide this. Regarding the uniparc customise column issue, I'll start a chat in the UX channel.

**Comment by aurel-l** [comment]
I think a quick fix for now would be to set size=500 by default for these cases. Most of the time people won't notice that there's a problem (while with the default of 25 they definitely will). And then we can ask backend to add the streaming endpoint later.

**Review by aurel-l — APPROVED** [review]
Approving in theory, but I guess pending discussion with Marija

**Pull request merged**
