### PR TITLE
keywords

### PR DESCRIPTION
**Pull request by aurel-l**
avoid categorising then flattening, and take into account possible empty array

### CODE REVIEW

**Comment by xwatkins** [comment]
While it looks neater and is probably slightly more performant (and with the size of list we're dealing with, it's likely irrelevant), I would be inclined to keep the current approach:
`getKeywordsForCategories` is used in multiple places, so a change in the logic required to do this grouping/filtering only needs to be done in one place.

**Comment by aurel-l** [comment]
Note that, additionally to that, it also returns a list of keywords in an expected alphabetical order (otherwise they're grouped by category, then alphabetically, but the user doesn't know that and it looks like they're mixed), and it covers the case where you end up with an empty list of keywords (see the 2 empty `small > div.keyword-view--inline` in your snapshots)

**Comment by xwatkins** [comment]
https://www.ebi.ac.uk/panda/jira/browse/TRM-22668

Fixing the empty list issue on the branch

**Comment by aurel-l** [comment]
Changes made in #494

**Pull request closed without merging**
