### PR TITLE
2021 06 peptide search result

### PR DESCRIPTION
**Pull request by dlrice**
Apologies, had issues merging my other branch so created a new one.

## Purpose
Create peptide search results [jira](https://www.ebi.ac.uk/panda/jira/browse/TRM-25641)

## Approach
* Use and augment newly refactored hooks.
* As Franklin's `PageIntro` component has changed refactored those places it's used in the site:
  * InfoMapping is reduced to providing a mapping from namespace or job type/tool to title
  * Info pages become placeholder landing pages for future developement

## Testing
Snapshot

## Checklist
- [x] My PR is scoped properly, and “does one thing only”
- [x] I have reviewed my own code
- [x] I have checked that linting checks pass and type safety is respected
- [x] I have checked that tests pass and coverage has at least improved, and if not explained the reasons why

### CODE REVIEW

**Comment by aurel-l** [comment]
Screenshot 2021-05-17 at 09 05 25
Slight issue when switching facets, when the data is loading it's missing a number in the sentence. Either it shouldn't display the sentence at all, or display the previous number with the sentence greyed out (like for the facet when they are loading)

**Comment by aurel-l** [comment]
I also think that the download is not working when facets are applied. It does show the right number of items (for example, I filter by reviewed, I have 2 results, download all gives me 2 items), but the items are not the correct ones, they are not the ones visible at that time with the facets applied.

**Review by aurel-l — CHANGES_REQUESTED** [review]
Reviewed the code and functionality, it looks like it's just missing a fix for the issue I raised https://github.com/ebi-uniprot/uniprot-website/pull/363#issuecomment-842115999 but the rest works fine and the code is looking good 👍🏽

**Comment by dlrice** [comment]
> Reviewed the code and functionality, it looks like it's just missing a fix for the issue I raised [#363 (comment)](https://github.com/ebi-uniprot/uniprot-website/pull/363#issuecomment-842115999) but the rest works fine and the code is looking good 👍🏽

Addressed the facet download issue. Also added an ` AND ` between the standard download query and facets - apparently not essential but the query looks neater this way.

**Review by aurel-l — APPROVED** [review]
Looks like it's working fine now 👍🏽

**Pull request merged**
