### PR TITLE
2021 08 use useBasket

### PR DESCRIPTION
**Pull request by aurel-l**
## Purpose
use useBasket around the website [TRM-26120](https://www.ebi.ac.uk/panda/jira/browse/TRM-26120) excluding the subtask about using the bubble component (need franklin changes).

## Approach
 - Change basket from object of Sets, to Map of Sets (was helping with types and simplifying the code)
 - Add a Map as a caching layer on top of localStorage to avoid reading from it too much (especially in result pages where each accession cell uses a useBasket hook)
 - Add a basket icon next to most of the accessions around the website
   - In entry pages, on the right of the title
   - In result page, on the left of the accession in the table view
   - In result page, on the top right of the card in the card view 
 - Clicking on the basket icon marking the presence of the accession removes it from the basket
 - Use more `AccessionView` around the website
 - Other fixes here and there

## Testing
 - Update snapshots

## Checklist
- [ ] My PR is scoped properly, and “does one thing only”
- [x] I have reviewed my own code
- [x] I have checked that linting checks pass and type safety is respected
- [x] I have checked that tests pass and coverage has at least improved, and if not explained the reasons why

### CODE REVIEW

**Review by xwatkins — CHANGES_REQUESTED** [review]
Code looks great.
Functionality/UI I'm unsure about a few things, some of which we should probably discuss with UX:
- The basket icon is a bit lost in the cards. I think it would be good to have a consistent way to display the icon with the accession, which is why I was suggesting after the accession in the results table, cards and entry
- Entry shouldn't display an active Add to basket button if the entry is in the basket already
- The basket icon in the entry should match the header size (if there's a way, we should look into having icon sizes for `.medium`, `.large` etc...)
- I'm not sure about the click to remove behaviour. I would have expected to open the basket instead (but that's just me).

**Comment by xwatkins** [comment]
> Code looks great.
> Functionality/UI I'm unsure about a few things, some of which we should probably discuss with UX:
> 
> * The basket icon is a bit lost in the cards. I think it would be good to have a consistent way to display the icon with the accession, which is why I was suggesting after the accession in the results table, cards and entry
> * Entry shouldn't display an active Add to basket button if the entry is in the basket already
> * The basket icon in the entry should match the header size (if there's a way, we should look into having icon sizes for `.medium`, `.large` etc...)
> * I'm not sure about the click to remove behaviour. I would have expected to open the basket instead (but that's just me).

Update: had a chat with Marija and she is making mockups.

**Comment by aurel-l** [comment]
OK, I guess I'll wait for the next design meeting to do any further change then

**Comment by xwatkins** [comment]
I think she'll just post to Slack as soon as she has something ready.
I would say you can go ahead and merge, and we can touch up afterwards.
One thing I was wondering, wouldn't it be less expensive to make just one call in the `Results` component and pass down the list of basket items instead of calling the (cached) dataset for every row?

**Comment by aurel-l** [comment]
> I would say you can go ahead and merge, and we can touch up afterwards

OK, will do, so that we can get the changed basket model to the main branch and start playing with the basket.

> One thing I was wondering, wouldn't it be less expensive to make just one call in the Results component and pass down the list of basket items instead of calling the (cached) dataset for every row?

I also think it _might_ be less expensive (might be the same actually thanks to the cache optimisation, but will certainly not be worse), but the refactor at different levels was not worth it at the time as it might require a model change (pass the basket status alongside the data to the data table) and possibly changes to the data table props if we need some different behaviour (we cannot easily remove from the table at the moment). I'm expecting some changes to the required specs once we start playing with it so I wanted to keep it simple for now, and do optimisations later.

> Entry shouldn't display an active Add to basket button if the entry is in the basket already

For example this is the kind of changes I assumed would come afterwards when playing with it. At the moment I tried to follow the current behaviour (an entry in the basket still has that button on its entry page) but I agree with you.
For example I would maybe want to untick the entries added to the basket after clicking on the button to add them, but I want more people to play with it before making that change and I'm sticking with what we have on the website at the moment.

**Comment by xwatkins** [comment]
> > I would say you can go ahead and merge, and we can touch up afterwards
> 
> OK, will do, so that we can get the changed basket model and the cache optimisation to the main branch and start playing with the basket.
> 
> > One thing I was wondering, wouldn't it be less expensive to make just one call in the Results component and pass down the list of basket items instead of calling the (cached) dataset for every row?
> 
> I also think it _might_ be less expensive (might be the same actually thanks to the cache optimisation, but will certainly not be worse), but the refactor at different levels was not worth it at the time as it might require a model change (pass the basket status alongside the data to the data table) and possibly changes to the data table props if we need some different behaviour (we cannot easily remove selection from the table logic at the moment). I'm expecting some changes to the required specs once we start playing with it so I wanted to keep it simple for now, and do optimisations later.
> 
> > Entry shouldn't display an active Add to basket button if the entry is in the basket already
> 
> For example this is the kind of changes I assumed would come afterwards when playing with it. At the moment I tried to follow the current behaviour (an entry in the basket still has that button on its entry page) but I agree with you.
> For example I would maybe want to untick the entries added to the basket after clicking on the button to add them, but I want more people to play with it before making that change and I'm sticking with what we have on the website at the moment.

👍  - I think the "add to basket" still being enabled on the current website is a bug BTW ;-)

**Review by xwatkins — APPROVED** [review]

**Comment by aurel-l** [comment]
Merging, but keeping the branch around to do more changes covered by the corresponding jira (will further PRs if needed though).
I've commented out the "remove from basket" logic in `BasketStatus` so that you @xwatkins can replace it with the logic to open the basket panel.

**Pull request merged**
