### PR TITLE
Unisave quick links

### PR DESCRIPTION
**Pull request by dlrice**
## Purpose
[Quick links to navigate nearby history diffs](https://www.ebi.ac.uk/panda/jira/browse/TRM-31208)

## Approach

- Created test cases then implemented function `getOtherDiffs`.
- Passed last version from top Entry component.

## Testing
Wrote unit tests but still needed to drop the coverage.

## Checklist
- [x] My PR is scoped properly, and “does one thing only”
- [x] I have reviewed my own code
- [x] I have checked that linting checks pass and type safety is respected
- [x] I have checked that tests pass and coverage has at least improved, and if not explained the reasons why

### CODE REVIEW

**Review by Swaathik — COMMENTED** [review]
In the UI, with the addition of new links, I find it is easy to miss what is currently being compared. Tagging @minjoonkim for some input. 

The logic looks fine and I played around and everything is OK.

**Comment by dlrice** [comment]
> In the UI, with the addition of new links, I find it is easy to miss what is currently being compared.

I see what you mean. How about giving the current viewed diffs bigger fontsize?

**Comment by dlrice** [comment]
Screenshot 2024-05-14 at 14 47 17

What do you think @Swaathik @minjoonkim ?

**Comment by minjoonkim** [comment]
Yep certainly looks better!
As long as it follows the font-size hierarchy I think we're good

**Comment by dlrice** [comment]
Yes, respects the header hierarchy. All good for merge @Swaathik?

**Pull request merged**
