### PR TITLE
Fix xref search "hack"

### PR DESCRIPTION
**Pull request by xwatkins**
## Purpose
Optimised xref query wasn't doing anything

## Approach
change the logic to handle this special case - replacing "xref" by "database" and the prefix value as value. Also added the parsing counterpart, which is only temporary until backend add the "database" field.

## Testing
Updated test case for xref and '*' search

## Checklist
- [x] My PR is scoped properly, and “does one thing only”
- [x] I have reviewed my own code
- [x] I have checked that linting checks pass and type safety is respected
- [x] I have checked that tests pass and coverage has at least improved, and if not explained the reasons why

### CODE REVIEW

**Review by aurel-l — APPROVED** [review]
Approved.

Would be good to have feedback about the warning sentence at the bottom at some point, after some users have tested it.
Wondering if that should be in a message pattern from Franklin, informational level.

**Comment by xwatkins** [comment]
> Approved.
> 
> Would be good to have feedback about the warning sentence at the bottom at some point, after some users have tested it.
> Wondering if that should be in a message pattern from Franklin, informational level.

That's a good point...we have the hero container but I'm not sure that's the right pattern here.

**Comment by aurel-l** [comment]
> > Approved.
> > Would be good to have feedback about the warning sentence at the bottom at some point, after some users have tested it.
> > Wondering if that should be in a message pattern from Franklin, informational level.
> 
> That's a good point...we have the hero container but I'm not sure that's the right pattern here.

Was talking about this component https://ebi-uniprot.github.io/franklin-sites/?path=/story/layout-message--default-message

**Comment by xwatkins** [comment]
> > > Approved.
> > > Would be good to have feedback about the warning sentence at the bottom at some point, after some users have tested it.
> > > Wondering if that should be in a message pattern from Franklin, informational level.
> > 
> > 
> > That's a good point...we have the hero container but I'm not sure that's the right pattern here.
> 
> Was talking about this component https://ebi-uniprot.github.io/franklin-sites/?path=/story/layout-message--default-message

I see. I don't think that's the right pattern either, messages are more to inform the user that something is happening

**Comment by xwatkins** [comment]
> > > > > Approved.
> > > > > Would be good to have feedback about the warning sentence at the bottom at some point, after some users have tested it.
> > > > > Wondering if that should be in a message pattern from Franklin, informational level.
> > > > 
> > > > 
> > > > That's a good point...we have the hero container but I'm not sure that's the right pattern here.
> > > 
> > > 
> > > Was talking about this component https://ebi-uniprot.github.io/franklin-sites/?path=/story/layout-message--default-message
> > 
> > 
> > I see. I don't think that's the right pattern either, messages are more to inform the user that something is happening
> 
> We use this in the warning message in the BLAST phylotree when we have negative values, as information in the dashboard when no job is present, for the "Caution" message in the UniProtKB entry page function section, etc. It's quite versatile already

Maybe we could have another session about the "purpose" and "function" of components in the next weeks - as I think the definitions are missing for a lot of new components. These really help deciding what to use where/when

**Pull request merged**
