### PR TITLE
2021 05 backend changes

### PR DESCRIPTION
**Pull request by aurel-l**
## Purpose
Update code to match new version of API

## Approach
- Go over everything and change wherever needed...
- Added an utility on network error to check if it's because of an invalid field to remove it from the storage (to prevent old values to stay and cause errors)

## Testing
Updated snapshots

## Checklist
- [x] My PR is scoped properly, and “does one thing only”
- [x] I have reviewed my own code
- [x] I have checked that linting checks pass and type safety is respected
- [x] I have checked that tests pass and coverage has at least improved, and if not explained the reasons why

Note: need to turn on the testing API flag

### CODE REVIEW

**Comment by xwatkins** [comment]
In proteomes `Overview.tsx`, the link in "Genome assembly and annotation" needs to be an external link

**Comment by xwatkins** [comment]
Databases, click on a category: `'category_facet' is not a valid search field` (e.g. links to http://localhost:8080/database?facets=category_facet:2D%20gel%20databases)

**Comment by xwatkins** [comment]
Pending citations check, looks good apart from the link issue above.

**Comment by aurel-l** [comment]
> In proteomes `Overview.tsx`, the link in "Genome assembly and annotation" needs to be an external link

Changed now. I didn't realise that this must also have been an issue before already.

> Databases, click on a category: 'category_facet' is not a valid search field (e.g. links to http://localhost:8080/database?facets=category_facet:2D%20gel%20databases)

This link is incorrect, this is not what is rendered on my machine so I can't get this situation. The correct link should be `category_exact`

**Comment by xwatkins** [comment]
> > Databases, click on a category: 'category_facet' is not a valid search field (e.g. links to http://localhost:8080/database?facets=category_facet:2D%20gel%20databases)
> 
> This link is incorrect, this is not what is rendered on my machine so I can't get this situation. The correct link should be `category_exact`

I think it's `DatabaseColumnConfiguration.tsx` L66?

**Comment by aurel-l** [comment]
> > > Databases, click on a category: 'category_facet' is not a valid search field (e.g. links to http://localhost:8080/database?facets=category_facet:2D%20gel%20databases)
> > 
> > 
> > This link is incorrect, this is not what is rendered on my machine so I can't get this situation. The correct link should be `category_exact`
> 
> I think it's `DatabaseColumnConfiguration.tsx` L66?

I see, I assumed you were clicking on the facets to get to that point. I have changed the column renderer now

**Comment by xwatkins** [comment]
In `getIdKeyForNamespace` L42, did you want to update  'key <string to be removed eventually>'?

**Comment by aurel-l** [comment]
> In `getIdKeyForNamespace` L42, did you want to update 'key '?

Done. Good catch, I forgot about that file

**Review by xwatkins — APPROVED** [review]

**Pull request merged**
